/*
Backup Management API

Testing ZeebeApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package camunda_backup_clients

import (
	"context"
	"testing"

	openapiclient "github.com/sijoma/camunda_backup_clients"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_camunda_backup_clients_ZeebeApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ZeebeApiService BackupIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var backupId int64

		httpRes, err := apiClient.ZeebeApi.BackupIdDelete(context.Background(), backupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZeebeApiService BackupIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var backupId int64

		resp, httpRes, err := apiClient.ZeebeApi.BackupIdGet(context.Background(), backupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZeebeApiService RootGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ZeebeApi.RootGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZeebeApiService RootPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ZeebeApi.RootPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
