/*
Backup Management API

Management endpoint to query, take, and delete backups of Zeebe.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package camunda_backup_clients

import (
	"encoding/json"
)

// TakeBackupResponse Request body for take backup
type TakeBackupResponse struct {
	// A message indicating backup has been triggered
	Message *string `json:"message,omitempty"`
}

// NewTakeBackupResponse instantiates a new TakeBackupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTakeBackupResponse() *TakeBackupResponse {
	this := TakeBackupResponse{}
	return &this
}

// NewTakeBackupResponseWithDefaults instantiates a new TakeBackupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTakeBackupResponseWithDefaults() *TakeBackupResponse {
	this := TakeBackupResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TakeBackupResponse) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TakeBackupResponse) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TakeBackupResponse) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TakeBackupResponse) SetMessage(v string) {
	o.Message = &v
}

func (o TakeBackupResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableTakeBackupResponse struct {
	value *TakeBackupResponse
	isSet bool
}

func (v NullableTakeBackupResponse) Get() *TakeBackupResponse {
	return v.value
}

func (v *NullableTakeBackupResponse) Set(val *TakeBackupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTakeBackupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTakeBackupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTakeBackupResponse(val *TakeBackupResponse) *NullableTakeBackupResponse {
	return &NullableTakeBackupResponse{value: val, isSet: true}
}

func (v NullableTakeBackupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTakeBackupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


